### ISSUE TITLE
Allow to pick one of enchant nodes

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/TradeCraft#19]
Shit, I knew I would forget one important thing.

I need to be able to specify different types of enchantments picked for items sold by vendors. So one vendor might:
1. Offer a Smite sword (with base being Smite II, and smaller chances for Smite III, Smite IV) ← this is possible now because highest enchant will win, if it’s picked.
2. _or_ offer a Bane of Arthropods sword for the same tier.

The second option isn’t possible. I am so sorry to talk about it so late, but without it I cannot launch. Can you make a feature for our nodes to pick one of many options? Can be ported straight out of Mantle:

``` yaml
- trade:
    comment: enchant
    itemA:
      currency: 10
    result:
      id: 257
      amount: 1
      enchants:
      - pick:
        - weights 3 1
        - enchant:
            id: 16
            level: 2,5
            chance: 1.0
            bonusAmountA: 10,20
            comment: sharpness
        - enchant:
            id: 13
            level: 2
            chance: 1.0
            bonusAmountA: 10,20
            comment: looting
```
