### ISSUE TITLE
Max range doesn’t appear to trigger

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/TradeCraft#24]
``` yaml
  Cleric:
    '0':
    - trade:
        comment: buying gold
        itemA:
          id: 266
          amount: 3,4
        result:
          currency: 1
```

As you can see, this is a trade randomizing number of gold ingots between 3 and 4.

However, I set up 22 platforms with Command Blocks spawning Clerics and **none** have the 4 option. It’s all 3. I didn’t notice it, Ginaw did.

Then I started checking other trades. Spider eyes, range from 8 to 11, only can get 8 to 10.

I’m sure it’s some silly oversight, can you check it?
