### ISSUE TITLE
Change all block/item IDs to use name system

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/TradeCraft#35]
I’m not sure how this is solved in Bukkit but I know that Minecraft is phasing away item and block IDs in 1.8. We need to jump on that train before it leaves and this is also a great opportunity to simplify our config and make it drastically smaller (our current trade config has **3,524** lines of text).
## Normal trade

``` yaml
- trade:
    itemA:
      currency: 1
    result:
      item: cake
- trade:
    itemA:
      currency: 1
    result:
      item: diamond_pickaxe,200
      amount: 2
- trade:
    itemA:
      currency: 1
    result:
      item: wool,yellow
      amount: 7,9
- trade:
    itemA:
      item: dye,black
      amount: 7,9
    result:
      currency: 1
```

Damage value would be provided after block’s / item’s name (which is taken directly from http://minecraft.gamepedia.com/Data_values). Special cases:
- Wool, stained clay, stained glass and carpet – colors
- Dyes – colors as well, they just don’t sync with wool (…) colors
## Enchantments

``` yaml
- enchant:
    sharpness: 2
- enchant:
    blast_protection: 1,2
    bonusAmountA: 2
```

This change turns 3-4 lines of config into 1-2 lines. Every enchant name is lowercase, and spaces are turned into `_` (which follows the block/item naming convention). Its level is specified on the right side and can vary just like any other value in the tree.
