### ISSUE TITLE
AI nerf doesn’t work

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/TradeCraft#43]
Have been standing 33+ blocks away from two villagers trapped in a 1 x 11 glass cage with pressure plates triggering redstone lanterns and even after waiting a few minutes outside of the range, they still were walking.

For the record

``` yaml
AILimiter:
  Enable: true
  MaximumDistanceToPlayer: 32
```
