### ISSUE TITLE
Metadata support?

### ISSUE THREAD

**Issue by Kongolan** [CoreNetwork/TradeCraft#49]
Is there any metadata support currently? I can't add lapis with:
    - trade:
        comment: selling lapis
        itemA:
          currency: 46,58
        result:
          item: dye:4
          amount: 1,2

**Comment by riddle** [comment]
``` yaml
  Shepherd:
    '0':
    - trade:
        comment: buying wool
        itemA:
          item: wool
          data: 0
          amount: 16,22
        result:
          currency: 1
```
