### ISSUE TITLE
Damage value isn’t respected

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/TradeCraft#5]
Two examples, might be impossible in 1.7?

Different wool colors

``` yaml
  Shepherd:
[snip]
    '1':
    - trade:
        comment: selling wool
        itemA:
          id: currency
          amount: 1
        result:
          id: 35
          damage: 1
          amount: 1,2
    - trade:
        comment: selling wool
        itemA:
          id: currency
          amount: 1
        result:
          id: 35
          damage: 2
          amount: 1,2
    - trade:
        comment: selling wool
        itemA:
          id: currency
          amount: 1
        result:
          id: 35
          damage: 3
          amount: 1,2
```

Specified charcoal, got coal

``` yaml
  Fisherman:
    '0':
    - trade:
        comment: buying coal
        itemA:
          id: 263
          damage: 1
          amount: 16,24
        result:
          id: currency
          amount: 1
```
