### ISSUE TITLE
Allow to define enchanted items

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/TradeCraft#9]
``` yaml
itemA:
    id: currency
    amount: 16,21
result:
    id: 276
    amount: 1
    enchants:
        - comment: sharpness
          id: 16
          levels: 2,3
          chance: 1.0
        - comment: looting
          id: 21
          levels: 1,2
          chance: 0.2
          bonusAmountA: 10,12
```

Enchants array allows to specify enchants for item (weapon, tool, armor or enchanted book). Every enchant has a chance (default `1.0`), array for levels (picked randomly) and optional `bonusAmountA`/`bonusAmountB` which will increase amount for `itemA` or `itemB` (in this case, increasing price in currency for 10, 11 or 12 emeralds).
